# Generated by Django 3.2.24 on 2024-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('dnd', 'DnD'), ('add', 'ADD'), ('dmg', 'DMG'), ('dungeonmaster', 'DungeonMaster')], default='normal', max_length=32),
        ),
    ]
