# Generated by Django 3.2.24 on 2024-02-09 15:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
