# Generated by Django 3.2.24 on 2024-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndevent',
            name='event_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dndevent',
            name='game_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dndevent',
            name='game_master',
            field=models.CharField(max_length=255),
        ),
    ]
