# Generated by Django 3.2.24 on 2024-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_events', '0002_auto_20240302_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndevent',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
    ]
